# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-23 11:49
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0007_alter_validators_add_error_messages'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='LookupTaskFrequency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequency_or_day', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='LookupTaskUrgency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('urgency', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_desc', models.CharField(max_length=64)),
                ('group_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='auth.Group')),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('email', models.EmailField(max_length=64)),
                ('role_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vsu_tms_app.Role')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StaffRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vsu_tms_app.Role')),
                ('staff_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vsu_tms_app.Staff')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_desc', models.CharField(max_length=128)),
                ('assigned_role_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned', to='vsu_tms_app.Role')),
                ('responsible_role_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responsible', to='vsu_tms_app.Role')),
                ('task_frequency_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vsu_tms_app.LookupTaskFrequency')),
                ('task_urgency_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vsu_tms_app.LookupTaskUrgency')),
            ],
        ),
        migrations.CreateModel(
            name='TaskList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_valid_for', models.DateField()),
                ('datetime_created', models.DateTimeField(auto_now=True)),
                ('created_by_user_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TaskListItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complete', models.BooleanField(default=False)),
                ('notes', models.CharField(blank=True, max_length=128)),
                ('time_due', models.DateTimeField()),
                ('task_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vsu_tms_app.Task')),
                ('tasklist_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vsu_tms_app.TaskList')),
            ],
        ),
        migrations.AddField(
            model_name='auditlog',
            name='tasklist_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vsu_tms_app.TaskListItem'),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
