# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-17 11:09
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vsu_tms_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LookupTaskFrequency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequency_or_day', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='LookupTaskUrgency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('urgency', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_desc', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StaffRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vsu_tms_app.Role')),
                ('staff_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vsu_tms_app.Staff')),
            ],
        ),
        migrations.CreateModel(
            name='TaskList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_valid_for', models.DateField()),
                ('datetime_created', models.DateTimeField(auto_now=True)),
                ('created_by_user_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TaskListItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complete', models.BooleanField(default=False)),
                ('notes', models.CharField(max_length=128)),
                ('time_due', models.DateTimeField()),
            ],
        ),
        migrations.RemoveField(
            model_name='task',
            name='test_id',
        ),
        migrations.AddField(
            model_name='task',
            name='task_desc',
            field=models.CharField(default=None, max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tasklistitem',
            name='task_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vsu_tms_app.Task'),
        ),
        migrations.AddField(
            model_name='tasklistitem',
            name='tasklist_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vsu_tms_app.TaskList'),
        ),
        migrations.AddField(
            model_name='task',
            name='assigned_role_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='assigned', to='vsu_tms_app.Role'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='responsible_role_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='responsible', to='vsu_tms_app.Role'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='task_frequency_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='vsu_tms_app.LookupTaskFrequency'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='task_urgency_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='vsu_tms_app.LookupTaskUrgency'),
            preserve_default=False,
        ),
    ]
