# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-18 11:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0007_alter_validators_add_error_messages'),
        ('vsu_tms_app', '0003_staff_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='group_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='auth.Group'),
            preserve_default=False,
        ),
    ]
