# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-18 12:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vsu_tms_app', '0005_auditlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasklistitem',
            name='notes',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
