# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-18 14:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vsu_tms_app', '0005_auditlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='role_id',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, to='vsu_tms_app.Role'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tasklistitem',
            name='notes',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
